apiVersion: batch/v1
kind: Job
metadata:
  name: evaluate-2p
  namespace: studbernstetter
  annotations:
    description: "evaluate"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/initial/evaluation/evaluate_synthetic_data_results.py"
            - "--results_dir=/home/stud/bernstetter/models/synthetic_twitch/ungrouped_results/hamilton/glove/"
            - "--results_fn=cosine.tsv"
            - "--word_column=1"
            - "--pseudoword_design_dict=/home/stud/bernstetter/datasets/synthetic_twitch/pseudoword_dict.json"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
