apiVersion: batch/v1
kind: Job
metadata:
  name: baseline-cp-full
  namespace: studbernstetter
  annotations:
    description: "detect changepoint"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "13"
              memory: "32Gi"
            requests:
              cpu: "4"
              memory: "8Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/semantic_change_detection/change_point_detection.py"
            - "--models_rootdir=/home/stud/bernstetter/models/twitch_multimodal/full_word_embeddings/"
            - "--outfiles_dir=/home/stud/bernstetter/models/twitch_multimodal/full_results/word_changepoint/sg0"
              #- "--targets=/home/stud/bernstetter/ma/mainrepo/data/emotes/2021"
            - "--distance_measure=cosine"
            - "--vector_size=128"
            - "--min_count=500"
            - "--skipgram=0"
            - "--no_of_iter=10"
            - "--z_scores"
            - "--align_to=last"
            - "--compare_to=last"
            - "--vocab_threshold=75"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
