apiVersion: batch/v1
kind: Job
metadata:
  name: twitch-cp-sg0-last
  namespace: studbernstetter
  annotations:
    description: "detect changepoint"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "12"
              memory: "32Gi"
            requests:
              cpu: "4"
              memory: "8Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/semantic_change_detection/change_point_detection.py"
            - "--models_rootdir=/home/stud/bernstetter/models/twitch/ungrouped/"
            - "--outfiles_dir=/home/stud/bernstetter/models/twitch/ungrouped_results/changepoint/sg0_targets_meanshifttest/"
            - "--targets=/home/stud/bernstetter/ma/mainrepo/data/targets/twitch_targets.csv"
            - "--distance_measure=cosine"
            - "--k_neighbors=25"
            - "--min_count=100"
            - "--skipgram=1"
            - "--no_of_iter=10"
            - "--word2vec=1"
            - "--z_scores"
            - "--align_to=last"
            - "--compare_to=last"
            - "--vocab_threshold=75"
            - "--clean=0"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
