apiVersion: batch/v1
kind: Job
metadata:
  name: build-vocab-{{ month }}
  namespace: studbernstetter
  annotations:
    description: "create global vocab with emotes"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "2"
              memory: "16Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/multimodal/vocab.py"
            - "--infiles_rootdir=/home/stud/bernstetter/datasets/twitch_multimodal/full/{{ month }}"
            - "--outdir_path=/home/stud/bernstetter/datasets/twitch_multimodal/full/global_vocabs/{{ month }}_multimodal_vocab.json"
            - "--min=500"
            - "--em_min=100"
            - "--skip_emotes=0"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
