apiVersion: batch/v1
kind: Job
metadata:
  name: changepoint-sg0-global-noemotes
  namespace: studbernstetter
  annotations:
    description: "detect change"
spec:
  template:
    spec:
      priorityClassName: research-low
      containers:
        - name: pytorch
          image: lsx-harbor.informatik.uni-wuerzburg.de/containers/pytorch:latest
          imagePullPolicy: "Always"
          resources:
            limits:
                    #nvidia.com/gpu: "1"
              cpu: "13"
              memory: "32Gi"
            requests:
                    #nvidia.com/gpu: "1"
              cpu: "1"
              memory: "4Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/multimodal/changepoint_lsc.py"
            - "--models_rootdir=/home/stud/bernstetter/models/twitch_multimodal/synth_fused_embeddings/sg0/global_vocab_noemotes"
            - "--outfiles_dir=/home/stud/bernstetter/models/twitch_multimodal/synth_results/changepoint/sg0/global_vocab_noemotes/"
            - "--align_to=last"
            - "--compare_to=last"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
