apiVersion: batch/v1
kind: Job
metadata:
  name: embedding-{{ month }}-sg1
  namespace: studbernstetter
  annotations:
    description: "creating embeddings"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "5"
              memory: "16Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/multimodal/embeddings.py"
            - "--input_dir=/home/stud/bernstetter/datasets/twitch_multimodal/synthetic/subsampled_70/{{ month }}.tsv"
            - "--model_dir=/home/stud/bernstetter/models/twitch_multimodal/synth_word_embeddings_noemotes/{{ month }}"
            - "--worker_count=5"
            - "--skipgram=1"
            - "--epoch_count=10"
            - "--word_min_count=100"
            - "--vector_size=512"
            - "--window_size=5"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
