apiVersion: batch/v1
kind: Job
metadata:
  name: twopoint-fused-gpu
  namespace: studbernstetter
  annotations:
    description: "detect change"
spec:
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: pytorch
          image: lsx-harbor.informatik.uni-wuerzburg.de/containers/pytorch:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "8"
              memory: "8Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: "4Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/multimodal/twopoint_lsc.py"
            - "--model1_filepath=/home/stud/bernstetter/models/twitch_multimodal/fused_embeddings/sg1_images/201905_fused_vectors.pt"
            - "--model2_filepath=/home/stud/bernstetter/models/twitch_multimodal/fused_embeddings/sg1_images/202004_fused_vectors.pt"
            - "--outfiles_dir=/home/stud/bernstetter/models/twitch_multimodal/results/twopoint/sg1_images/"
            - "--t_best=5000"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
