apiVersion: batch/v1
kind: Job
metadata:
  name: create-synth-test
  namespace: studbernstetter
  annotations:
    description: ""
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "10"
              memory: "20Gi"
            requests:
              cpu: "4"
              memory: "8Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/synthetic_data_generation/create_synthetic_dataset.py"
            - "--input_filepath=/home/stud/bernstetter/datasets/twitch_multimodal/201911_em_concat.tsv"
            - "--outfiles_rootdir=/home/stud/bernstetter/datasets/twitch_multimodal/synth_test/"
            - "--context_word_dict_filepath=/home/stud/bernstetter/datasets/twitch_multimodal/synthetic/context_word_dict.json"
            - "--pseudoword_dict_filepath=/home/stud/bernstetter/datasets/twitch_multimodal/synthetic/pseudoword_dict.json"
            - "--start_year=2019"
            - "--start_month=5"
            - "--end_year=2020"
            - "--end_month=4"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
