apiVersion: batch/v1
kind: Job
metadata:
  name: durel-twostep
  namespace: studbernstetter
  annotations:
    description: "detect change"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "8"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/semantic_change_detection/hamilton_durel.py"
            - "--model1_filepath=/home/stud/bernstetter/models/woc_reproduce/dta18/vec_300_w5_mc25_iter5_sg1_lc0_clean0_w2v1/saved_model.gensim"
            - "--model2_filepath=/home/stud/bernstetter/models/woc_reproduce/dta19/vec_300_w5_mc37_iter5_sg1_lc0_clean0_w2v1/saved_model.gensim"
            - "--outfiles_dir=/home/stud/bernstetter/models/woc_reproduce/results/durel"
            - "--targets=/home/stud/bernstetter/ma/mainrepo/data/targets/durel_targets.csv"
            - "--t_best=100"
            - "--cosine" 
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
