apiVersion: batch/v1
kind: Job
metadata:
  name: prep-202104-h1
  namespace: studbernstetter
  annotations:
    description: "template for doing anything in my home"
spec:
  template:
    spec:
      priorityClassName: research-low
      imagePullSecrets:
        - name: gitlab-registry-bernstetter
      containers:
        - name: pythonbase
          image: gitlab2.informatik.uni-wuerzburg.de:4567/s319059/containers/pythonbase
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "12"
              memory: "64Gi"
            requests:
              cpu: "6"
              memory: "16Gi"
          command:
            - "python3"
            - "/home/stud/bernstetter/ma/mainrepo/preprocessing/preprocessing.py"
            - "--infiles_rootdir=/home/stud/bernstetter/datasets/twitch/202104/raw/H1/"
            - "--outfiles_dir=/home/stud/bernstetter/datasets/twitch/202104/clean_en_sorted/H1/"
            - "--multi=1"
            - "--ffz=/home/stud/bernstetter/ma/mainrepo/data/emotes/2021/ffz_emotes.csv"
            - "--bttv=/home/stud/bernstetter/ma/mainrepo/data/emotes/2021/bttv_global_emotes.csv"
          volumeMounts:
            - mountPath: /home/stud/bernstetter
              name: home
            - mountPath: /media/kobs/twitch/djinn4
              name: media
      restartPolicy: "Never"
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/home/stud/bernstetter"
            secretRef:
              name: ceph-secret-studbernstetter
        - name: media
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studbernstetter
            path: "/vaudience/djinn4"
            secretRef:
              name: ceph-secret-studbernstetter
